server:
  port: 7002

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server7002
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

