server:
  port: 7100
spring:
  application:
    name: config-server
  cloud:
    # git配置
    config:
      server:
        git:
          uri: https://gitee.com/ran_kunchi/config-cloud
          username: 17602382966
          password: qqq111222333
          timeout: 5
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/